// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_rpc_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_rpc_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_rpc_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_rpc_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_rpc_2eproto;
namespace tiny_muduo_rpc {
class RpcMessage;
struct RpcMessageDefaultTypeInternal;
extern RpcMessageDefaultTypeInternal _RpcMessage_default_instance_;
}  // namespace tiny_muduo_rpc
PROTOBUF_NAMESPACE_OPEN
template<> ::tiny_muduo_rpc::RpcMessage* Arena::CreateMaybeMessage<::tiny_muduo_rpc::RpcMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace tiny_muduo_rpc {

enum MessageType : int {
  REQUEST = 0,
  RESPONSE = 1,
  ERROR = 2,
  MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MessageType_IsValid(int value);
constexpr MessageType MessageType_MIN = REQUEST;
constexpr MessageType MessageType_MAX = ERROR;
constexpr int MessageType_ARRAYSIZE = MessageType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageType_descriptor();
template<typename T>
inline const std::string& MessageType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MessageType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MessageType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MessageType_descriptor(), enum_t_value);
}
inline bool MessageType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MessageType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MessageType>(
    MessageType_descriptor(), name, value);
}
enum ErrorCode : int {
  NO_ERROR = 0,
  WRONG_PROTO = 1,
  NO_SERVICE = 2,
  NO_METHOD = 3,
  INVALID_REQUEST = 4,
  INVALID_RESPONSE = 5,
  TIMEOUT = 6,
  ErrorCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ErrorCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ErrorCode_IsValid(int value);
constexpr ErrorCode ErrorCode_MIN = NO_ERROR;
constexpr ErrorCode ErrorCode_MAX = TIMEOUT;
constexpr int ErrorCode_ARRAYSIZE = ErrorCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ErrorCode_descriptor();
template<typename T>
inline const std::string& ErrorCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ErrorCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ErrorCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ErrorCode_descriptor(), enum_t_value);
}
inline bool ErrorCode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ErrorCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ErrorCode>(
    ErrorCode_descriptor(), name, value);
}
// ===================================================================

class RpcMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tiny_muduo_rpc.RpcMessage) */ {
 public:
  inline RpcMessage() : RpcMessage(nullptr) {}
  ~RpcMessage() override;
  explicit PROTOBUF_CONSTEXPR RpcMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RpcMessage(const RpcMessage& from);
  RpcMessage(RpcMessage&& from) noexcept
    : RpcMessage() {
    *this = ::std::move(from);
  }

  inline RpcMessage& operator=(const RpcMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline RpcMessage& operator=(RpcMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RpcMessage& default_instance() {
    return *internal_default_instance();
  }
  enum OptionalServiceCase {
    kService = 3,
    OPTIONAL_SERVICE_NOT_SET = 0,
  };

  enum OptionalMethodCase {
    kMethod = 4,
    OPTIONAL_METHOD_NOT_SET = 0,
  };

  enum OptionalRequestCase {
    kRequest = 5,
    OPTIONAL_REQUEST_NOT_SET = 0,
  };

  enum OptionalResponseCase {
    kResponse = 6,
    OPTIONAL_RESPONSE_NOT_SET = 0,
  };

  enum OptionalErrorCase {
    kError = 7,
    OPTIONAL_ERROR_NOT_SET = 0,
  };

  static inline const RpcMessage* internal_default_instance() {
    return reinterpret_cast<const RpcMessage*>(
               &_RpcMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RpcMessage& a, RpcMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(RpcMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RpcMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RpcMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RpcMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RpcMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const RpcMessage& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RpcMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tiny_muduo_rpc.RpcMessage";
  }
  protected:
  explicit RpcMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 2,
    kTypeFieldNumber = 1,
    kServiceFieldNumber = 3,
    kMethodFieldNumber = 4,
    kRequestFieldNumber = 5,
    kResponseFieldNumber = 6,
    kErrorFieldNumber = 7,
  };
  // fixed64 id = 2;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // .tiny_muduo_rpc.MessageType type = 1;
  void clear_type();
  ::tiny_muduo_rpc::MessageType type() const;
  void set_type(::tiny_muduo_rpc::MessageType value);
  private:
  ::tiny_muduo_rpc::MessageType _internal_type() const;
  void _internal_set_type(::tiny_muduo_rpc::MessageType value);
  public:

  // string service = 3;
  bool has_service() const;
  private:
  bool _internal_has_service() const;
  public:
  void clear_service();
  const std::string& service() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_service(ArgT0&& arg0, ArgT... args);
  std::string* mutable_service();
  PROTOBUF_NODISCARD std::string* release_service();
  void set_allocated_service(std::string* service);
  private:
  const std::string& _internal_service() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_service(const std::string& value);
  std::string* _internal_mutable_service();
  public:

  // string method = 4;
  bool has_method() const;
  private:
  bool _internal_has_method() const;
  public:
  void clear_method();
  const std::string& method() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_method(ArgT0&& arg0, ArgT... args);
  std::string* mutable_method();
  PROTOBUF_NODISCARD std::string* release_method();
  void set_allocated_method(std::string* method);
  private:
  const std::string& _internal_method() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_method(const std::string& value);
  std::string* _internal_mutable_method();
  public:

  // bytes request = 5;
  bool has_request() const;
  private:
  bool _internal_has_request() const;
  public:
  void clear_request();
  const std::string& request() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_request(ArgT0&& arg0, ArgT... args);
  std::string* mutable_request();
  PROTOBUF_NODISCARD std::string* release_request();
  void set_allocated_request(std::string* request);
  private:
  const std::string& _internal_request() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_request(const std::string& value);
  std::string* _internal_mutable_request();
  public:

  // bytes response = 6;
  bool has_response() const;
  private:
  bool _internal_has_response() const;
  public:
  void clear_response();
  const std::string& response() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_response(ArgT0&& arg0, ArgT... args);
  std::string* mutable_response();
  PROTOBUF_NODISCARD std::string* release_response();
  void set_allocated_response(std::string* response);
  private:
  const std::string& _internal_response() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_response(const std::string& value);
  std::string* _internal_mutable_response();
  public:

  // .tiny_muduo_rpc.ErrorCode error = 7;
  bool has_error() const;
  private:
  bool _internal_has_error() const;
  public:
  void clear_error();
  ::tiny_muduo_rpc::ErrorCode error() const;
  void set_error(::tiny_muduo_rpc::ErrorCode value);
  private:
  ::tiny_muduo_rpc::ErrorCode _internal_error() const;
  void _internal_set_error(::tiny_muduo_rpc::ErrorCode value);
  public:

  void clear_optional_service();
  OptionalServiceCase optional_service_case() const;
  void clear_optional_method();
  OptionalMethodCase optional_method_case() const;
  void clear_optional_request();
  OptionalRequestCase optional_request_case() const;
  void clear_optional_response();
  OptionalResponseCase optional_response_case() const;
  void clear_optional_error();
  OptionalErrorCase optional_error_case() const;
  // @@protoc_insertion_point(class_scope:tiny_muduo_rpc.RpcMessage)
 private:
  class _Internal;
  void set_has_service();
  void set_has_method();
  void set_has_request();
  void set_has_response();
  void set_has_error();

  inline bool has_optional_service() const;
  inline void clear_has_optional_service();

  inline bool has_optional_method() const;
  inline void clear_has_optional_method();

  inline bool has_optional_request() const;
  inline void clear_has_optional_request();

  inline bool has_optional_response() const;
  inline void clear_has_optional_response();

  inline bool has_optional_error() const;
  inline void clear_has_optional_error();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint64_t id_;
  int type_;
  union OptionalServiceUnion {
    constexpr OptionalServiceUnion() : _constinit_{} {}
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr service_;
  } optional_service_;
  union OptionalMethodUnion {
    constexpr OptionalMethodUnion() : _constinit_{} {}
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr method_;
  } optional_method_;
  union OptionalRequestUnion {
    constexpr OptionalRequestUnion() : _constinit_{} {}
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr request_;
  } optional_request_;
  union OptionalResponseUnion {
    constexpr OptionalResponseUnion() : _constinit_{} {}
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr response_;
  } optional_response_;
  union OptionalErrorUnion {
    constexpr OptionalErrorUnion() : _constinit_{} {}
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
    int error_;
  } optional_error_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  uint32_t _oneof_case_[5];

  friend struct ::TableStruct_rpc_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RpcMessage

// .tiny_muduo_rpc.MessageType type = 1;
inline void RpcMessage::clear_type() {
  type_ = 0;
}
inline ::tiny_muduo_rpc::MessageType RpcMessage::_internal_type() const {
  return static_cast< ::tiny_muduo_rpc::MessageType >(type_);
}
inline ::tiny_muduo_rpc::MessageType RpcMessage::type() const {
  // @@protoc_insertion_point(field_get:tiny_muduo_rpc.RpcMessage.type)
  return _internal_type();
}
inline void RpcMessage::_internal_set_type(::tiny_muduo_rpc::MessageType value) {
  
  type_ = value;
}
inline void RpcMessage::set_type(::tiny_muduo_rpc::MessageType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:tiny_muduo_rpc.RpcMessage.type)
}

// fixed64 id = 2;
inline void RpcMessage::clear_id() {
  id_ = uint64_t{0u};
}
inline uint64_t RpcMessage::_internal_id() const {
  return id_;
}
inline uint64_t RpcMessage::id() const {
  // @@protoc_insertion_point(field_get:tiny_muduo_rpc.RpcMessage.id)
  return _internal_id();
}
inline void RpcMessage::_internal_set_id(uint64_t value) {
  
  id_ = value;
}
inline void RpcMessage::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:tiny_muduo_rpc.RpcMessage.id)
}

// string service = 3;
inline bool RpcMessage::_internal_has_service() const {
  return optional_service_case() == kService;
}
inline bool RpcMessage::has_service() const {
  return _internal_has_service();
}
inline void RpcMessage::set_has_service() {
  _oneof_case_[0] = kService;
}
inline void RpcMessage::clear_service() {
  if (_internal_has_service()) {
    optional_service_.service_.Destroy();
    clear_has_optional_service();
  }
}
inline const std::string& RpcMessage::service() const {
  // @@protoc_insertion_point(field_get:tiny_muduo_rpc.RpcMessage.service)
  return _internal_service();
}
template <typename ArgT0, typename... ArgT>
inline void RpcMessage::set_service(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_service()) {
    clear_optional_service();
    set_has_service();
    optional_service_.service_.InitDefault();
  }
  optional_service_.service_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tiny_muduo_rpc.RpcMessage.service)
}
inline std::string* RpcMessage::mutable_service() {
  std::string* _s = _internal_mutable_service();
  // @@protoc_insertion_point(field_mutable:tiny_muduo_rpc.RpcMessage.service)
  return _s;
}
inline const std::string& RpcMessage::_internal_service() const {
  if (_internal_has_service()) {
    return optional_service_.service_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void RpcMessage::_internal_set_service(const std::string& value) {
  if (!_internal_has_service()) {
    clear_optional_service();
    set_has_service();
    optional_service_.service_.InitDefault();
  }
  optional_service_.service_.Set(value, GetArenaForAllocation());
}
inline std::string* RpcMessage::_internal_mutable_service() {
  if (!_internal_has_service()) {
    clear_optional_service();
    set_has_service();
    optional_service_.service_.InitDefault();
  }
  return optional_service_.service_.Mutable(      GetArenaForAllocation());
}
inline std::string* RpcMessage::release_service() {
  // @@protoc_insertion_point(field_release:tiny_muduo_rpc.RpcMessage.service)
  if (_internal_has_service()) {
    clear_has_optional_service();
    return optional_service_.service_.Release();
  } else {
    return nullptr;
  }
}
inline void RpcMessage::set_allocated_service(std::string* service) {
  if (has_optional_service()) {
    clear_optional_service();
  }
  if (service != nullptr) {
    set_has_service();
    optional_service_.service_.InitAllocated(service, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:tiny_muduo_rpc.RpcMessage.service)
}

// string method = 4;
inline bool RpcMessage::_internal_has_method() const {
  return optional_method_case() == kMethod;
}
inline bool RpcMessage::has_method() const {
  return _internal_has_method();
}
inline void RpcMessage::set_has_method() {
  _oneof_case_[1] = kMethod;
}
inline void RpcMessage::clear_method() {
  if (_internal_has_method()) {
    optional_method_.method_.Destroy();
    clear_has_optional_method();
  }
}
inline const std::string& RpcMessage::method() const {
  // @@protoc_insertion_point(field_get:tiny_muduo_rpc.RpcMessage.method)
  return _internal_method();
}
template <typename ArgT0, typename... ArgT>
inline void RpcMessage::set_method(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_method()) {
    clear_optional_method();
    set_has_method();
    optional_method_.method_.InitDefault();
  }
  optional_method_.method_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tiny_muduo_rpc.RpcMessage.method)
}
inline std::string* RpcMessage::mutable_method() {
  std::string* _s = _internal_mutable_method();
  // @@protoc_insertion_point(field_mutable:tiny_muduo_rpc.RpcMessage.method)
  return _s;
}
inline const std::string& RpcMessage::_internal_method() const {
  if (_internal_has_method()) {
    return optional_method_.method_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void RpcMessage::_internal_set_method(const std::string& value) {
  if (!_internal_has_method()) {
    clear_optional_method();
    set_has_method();
    optional_method_.method_.InitDefault();
  }
  optional_method_.method_.Set(value, GetArenaForAllocation());
}
inline std::string* RpcMessage::_internal_mutable_method() {
  if (!_internal_has_method()) {
    clear_optional_method();
    set_has_method();
    optional_method_.method_.InitDefault();
  }
  return optional_method_.method_.Mutable(      GetArenaForAllocation());
}
inline std::string* RpcMessage::release_method() {
  // @@protoc_insertion_point(field_release:tiny_muduo_rpc.RpcMessage.method)
  if (_internal_has_method()) {
    clear_has_optional_method();
    return optional_method_.method_.Release();
  } else {
    return nullptr;
  }
}
inline void RpcMessage::set_allocated_method(std::string* method) {
  if (has_optional_method()) {
    clear_optional_method();
  }
  if (method != nullptr) {
    set_has_method();
    optional_method_.method_.InitAllocated(method, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:tiny_muduo_rpc.RpcMessage.method)
}

// bytes request = 5;
inline bool RpcMessage::_internal_has_request() const {
  return optional_request_case() == kRequest;
}
inline bool RpcMessage::has_request() const {
  return _internal_has_request();
}
inline void RpcMessage::set_has_request() {
  _oneof_case_[2] = kRequest;
}
inline void RpcMessage::clear_request() {
  if (_internal_has_request()) {
    optional_request_.request_.Destroy();
    clear_has_optional_request();
  }
}
inline const std::string& RpcMessage::request() const {
  // @@protoc_insertion_point(field_get:tiny_muduo_rpc.RpcMessage.request)
  return _internal_request();
}
template <typename ArgT0, typename... ArgT>
inline void RpcMessage::set_request(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_request()) {
    clear_optional_request();
    set_has_request();
    optional_request_.request_.InitDefault();
  }
  optional_request_.request_.SetBytes( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tiny_muduo_rpc.RpcMessage.request)
}
inline std::string* RpcMessage::mutable_request() {
  std::string* _s = _internal_mutable_request();
  // @@protoc_insertion_point(field_mutable:tiny_muduo_rpc.RpcMessage.request)
  return _s;
}
inline const std::string& RpcMessage::_internal_request() const {
  if (_internal_has_request()) {
    return optional_request_.request_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void RpcMessage::_internal_set_request(const std::string& value) {
  if (!_internal_has_request()) {
    clear_optional_request();
    set_has_request();
    optional_request_.request_.InitDefault();
  }
  optional_request_.request_.Set(value, GetArenaForAllocation());
}
inline std::string* RpcMessage::_internal_mutable_request() {
  if (!_internal_has_request()) {
    clear_optional_request();
    set_has_request();
    optional_request_.request_.InitDefault();
  }
  return optional_request_.request_.Mutable(      GetArenaForAllocation());
}
inline std::string* RpcMessage::release_request() {
  // @@protoc_insertion_point(field_release:tiny_muduo_rpc.RpcMessage.request)
  if (_internal_has_request()) {
    clear_has_optional_request();
    return optional_request_.request_.Release();
  } else {
    return nullptr;
  }
}
inline void RpcMessage::set_allocated_request(std::string* request) {
  if (has_optional_request()) {
    clear_optional_request();
  }
  if (request != nullptr) {
    set_has_request();
    optional_request_.request_.InitAllocated(request, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:tiny_muduo_rpc.RpcMessage.request)
}

// bytes response = 6;
inline bool RpcMessage::_internal_has_response() const {
  return optional_response_case() == kResponse;
}
inline bool RpcMessage::has_response() const {
  return _internal_has_response();
}
inline void RpcMessage::set_has_response() {
  _oneof_case_[3] = kResponse;
}
inline void RpcMessage::clear_response() {
  if (_internal_has_response()) {
    optional_response_.response_.Destroy();
    clear_has_optional_response();
  }
}
inline const std::string& RpcMessage::response() const {
  // @@protoc_insertion_point(field_get:tiny_muduo_rpc.RpcMessage.response)
  return _internal_response();
}
template <typename ArgT0, typename... ArgT>
inline void RpcMessage::set_response(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_response()) {
    clear_optional_response();
    set_has_response();
    optional_response_.response_.InitDefault();
  }
  optional_response_.response_.SetBytes( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tiny_muduo_rpc.RpcMessage.response)
}
inline std::string* RpcMessage::mutable_response() {
  std::string* _s = _internal_mutable_response();
  // @@protoc_insertion_point(field_mutable:tiny_muduo_rpc.RpcMessage.response)
  return _s;
}
inline const std::string& RpcMessage::_internal_response() const {
  if (_internal_has_response()) {
    return optional_response_.response_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void RpcMessage::_internal_set_response(const std::string& value) {
  if (!_internal_has_response()) {
    clear_optional_response();
    set_has_response();
    optional_response_.response_.InitDefault();
  }
  optional_response_.response_.Set(value, GetArenaForAllocation());
}
inline std::string* RpcMessage::_internal_mutable_response() {
  if (!_internal_has_response()) {
    clear_optional_response();
    set_has_response();
    optional_response_.response_.InitDefault();
  }
  return optional_response_.response_.Mutable(      GetArenaForAllocation());
}
inline std::string* RpcMessage::release_response() {
  // @@protoc_insertion_point(field_release:tiny_muduo_rpc.RpcMessage.response)
  if (_internal_has_response()) {
    clear_has_optional_response();
    return optional_response_.response_.Release();
  } else {
    return nullptr;
  }
}
inline void RpcMessage::set_allocated_response(std::string* response) {
  if (has_optional_response()) {
    clear_optional_response();
  }
  if (response != nullptr) {
    set_has_response();
    optional_response_.response_.InitAllocated(response, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:tiny_muduo_rpc.RpcMessage.response)
}

// .tiny_muduo_rpc.ErrorCode error = 7;
inline bool RpcMessage::_internal_has_error() const {
  return optional_error_case() == kError;
}
inline bool RpcMessage::has_error() const {
  return _internal_has_error();
}
inline void RpcMessage::set_has_error() {
  _oneof_case_[4] = kError;
}
inline void RpcMessage::clear_error() {
  if (_internal_has_error()) {
    optional_error_.error_ = 0;
    clear_has_optional_error();
  }
}
inline ::tiny_muduo_rpc::ErrorCode RpcMessage::_internal_error() const {
  if (_internal_has_error()) {
    return static_cast< ::tiny_muduo_rpc::ErrorCode >(optional_error_.error_);
  }
  return static_cast< ::tiny_muduo_rpc::ErrorCode >(0);
}
inline ::tiny_muduo_rpc::ErrorCode RpcMessage::error() const {
  // @@protoc_insertion_point(field_get:tiny_muduo_rpc.RpcMessage.error)
  return _internal_error();
}
inline void RpcMessage::_internal_set_error(::tiny_muduo_rpc::ErrorCode value) {
  if (!_internal_has_error()) {
    clear_optional_error();
    set_has_error();
  }
  optional_error_.error_ = value;
}
inline void RpcMessage::set_error(::tiny_muduo_rpc::ErrorCode value) {
  _internal_set_error(value);
  // @@protoc_insertion_point(field_set:tiny_muduo_rpc.RpcMessage.error)
}

inline bool RpcMessage::has_optional_service() const {
  return optional_service_case() != OPTIONAL_SERVICE_NOT_SET;
}
inline void RpcMessage::clear_has_optional_service() {
  _oneof_case_[0] = OPTIONAL_SERVICE_NOT_SET;
}
inline bool RpcMessage::has_optional_method() const {
  return optional_method_case() != OPTIONAL_METHOD_NOT_SET;
}
inline void RpcMessage::clear_has_optional_method() {
  _oneof_case_[1] = OPTIONAL_METHOD_NOT_SET;
}
inline bool RpcMessage::has_optional_request() const {
  return optional_request_case() != OPTIONAL_REQUEST_NOT_SET;
}
inline void RpcMessage::clear_has_optional_request() {
  _oneof_case_[2] = OPTIONAL_REQUEST_NOT_SET;
}
inline bool RpcMessage::has_optional_response() const {
  return optional_response_case() != OPTIONAL_RESPONSE_NOT_SET;
}
inline void RpcMessage::clear_has_optional_response() {
  _oneof_case_[3] = OPTIONAL_RESPONSE_NOT_SET;
}
inline bool RpcMessage::has_optional_error() const {
  return optional_error_case() != OPTIONAL_ERROR_NOT_SET;
}
inline void RpcMessage::clear_has_optional_error() {
  _oneof_case_[4] = OPTIONAL_ERROR_NOT_SET;
}
inline RpcMessage::OptionalServiceCase RpcMessage::optional_service_case() const {
  return RpcMessage::OptionalServiceCase(_oneof_case_[0]);
}
inline RpcMessage::OptionalMethodCase RpcMessage::optional_method_case() const {
  return RpcMessage::OptionalMethodCase(_oneof_case_[1]);
}
inline RpcMessage::OptionalRequestCase RpcMessage::optional_request_case() const {
  return RpcMessage::OptionalRequestCase(_oneof_case_[2]);
}
inline RpcMessage::OptionalResponseCase RpcMessage::optional_response_case() const {
  return RpcMessage::OptionalResponseCase(_oneof_case_[3]);
}
inline RpcMessage::OptionalErrorCase RpcMessage::optional_error_case() const {
  return RpcMessage::OptionalErrorCase(_oneof_case_[4]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace tiny_muduo_rpc

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::tiny_muduo_rpc::MessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::tiny_muduo_rpc::MessageType>() {
  return ::tiny_muduo_rpc::MessageType_descriptor();
}
template <> struct is_proto_enum< ::tiny_muduo_rpc::ErrorCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::tiny_muduo_rpc::ErrorCode>() {
  return ::tiny_muduo_rpc::ErrorCode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_rpc_2eproto
