// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpcservice.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_rpcservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_rpcservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
#include "rpc.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_rpcservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_rpcservice_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_rpcservice_2eproto;
namespace tiny_muduo_rpc {
class GetServiceRequest;
struct GetServiceRequestDefaultTypeInternal;
extern GetServiceRequestDefaultTypeInternal _GetServiceRequest_default_instance_;
class GetServiceResponse;
struct GetServiceResponseDefaultTypeInternal;
extern GetServiceResponseDefaultTypeInternal _GetServiceResponse_default_instance_;
class ListRpcRequest;
struct ListRpcRequestDefaultTypeInternal;
extern ListRpcRequestDefaultTypeInternal _ListRpcRequest_default_instance_;
class ListRpcResponse;
struct ListRpcResponseDefaultTypeInternal;
extern ListRpcResponseDefaultTypeInternal _ListRpcResponse_default_instance_;
}  // namespace tiny_muduo_rpc
PROTOBUF_NAMESPACE_OPEN
template<> ::tiny_muduo_rpc::GetServiceRequest* Arena::CreateMaybeMessage<::tiny_muduo_rpc::GetServiceRequest>(Arena*);
template<> ::tiny_muduo_rpc::GetServiceResponse* Arena::CreateMaybeMessage<::tiny_muduo_rpc::GetServiceResponse>(Arena*);
template<> ::tiny_muduo_rpc::ListRpcRequest* Arena::CreateMaybeMessage<::tiny_muduo_rpc::ListRpcRequest>(Arena*);
template<> ::tiny_muduo_rpc::ListRpcResponse* Arena::CreateMaybeMessage<::tiny_muduo_rpc::ListRpcResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace tiny_muduo_rpc {

// ===================================================================

class ListRpcRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tiny_muduo_rpc.ListRpcRequest) */ {
 public:
  inline ListRpcRequest() : ListRpcRequest(nullptr) {}
  ~ListRpcRequest() override;
  explicit PROTOBUF_CONSTEXPR ListRpcRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ListRpcRequest(const ListRpcRequest& from);
  ListRpcRequest(ListRpcRequest&& from) noexcept
    : ListRpcRequest() {
    *this = ::std::move(from);
  }

  inline ListRpcRequest& operator=(const ListRpcRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ListRpcRequest& operator=(ListRpcRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ListRpcRequest& default_instance() {
    return *internal_default_instance();
  }
  enum OptionalServiceNameCase {
    kServiceName = 1,
    OPTIONAL_SERVICE_NAME_NOT_SET = 0,
  };

  enum OptionalListMethodCase {
    kListMethod = 2,
    OPTIONAL_LIST_METHOD_NOT_SET = 0,
  };

  static inline const ListRpcRequest* internal_default_instance() {
    return reinterpret_cast<const ListRpcRequest*>(
               &_ListRpcRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ListRpcRequest& a, ListRpcRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ListRpcRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ListRpcRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ListRpcRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ListRpcRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ListRpcRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ListRpcRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ListRpcRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tiny_muduo_rpc.ListRpcRequest";
  }
  protected:
  explicit ListRpcRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServiceNameFieldNumber = 1,
    kListMethodFieldNumber = 2,
  };
  // string service_name = 1;
  bool has_service_name() const;
  private:
  bool _internal_has_service_name() const;
  public:
  void clear_service_name();
  const std::string& service_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_service_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_service_name();
  PROTOBUF_NODISCARD std::string* release_service_name();
  void set_allocated_service_name(std::string* service_name);
  private:
  const std::string& _internal_service_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_service_name(const std::string& value);
  std::string* _internal_mutable_service_name();
  public:

  // bool list_method = 2;
  bool has_list_method() const;
  private:
  bool _internal_has_list_method() const;
  public:
  void clear_list_method();
  bool list_method() const;
  void set_list_method(bool value);
  private:
  bool _internal_list_method() const;
  void _internal_set_list_method(bool value);
  public:

  void clear_optional_service_name();
  OptionalServiceNameCase optional_service_name_case() const;
  void clear_optional_list_method();
  OptionalListMethodCase optional_list_method_case() const;
  // @@protoc_insertion_point(class_scope:tiny_muduo_rpc.ListRpcRequest)
 private:
  class _Internal;
  void set_has_service_name();
  void set_has_list_method();

  inline bool has_optional_service_name() const;
  inline void clear_has_optional_service_name();

  inline bool has_optional_list_method() const;
  inline void clear_has_optional_list_method();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  union OptionalServiceNameUnion {
    constexpr OptionalServiceNameUnion() : _constinit_{} {}
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr service_name_;
  } optional_service_name_;
  union OptionalListMethodUnion {
    constexpr OptionalListMethodUnion() : _constinit_{} {}
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
    bool list_method_;
  } optional_list_method_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  uint32_t _oneof_case_[2];

  friend struct ::TableStruct_rpcservice_2eproto;
};
// -------------------------------------------------------------------

class ListRpcResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tiny_muduo_rpc.ListRpcResponse) */ {
 public:
  inline ListRpcResponse() : ListRpcResponse(nullptr) {}
  ~ListRpcResponse() override;
  explicit PROTOBUF_CONSTEXPR ListRpcResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ListRpcResponse(const ListRpcResponse& from);
  ListRpcResponse(ListRpcResponse&& from) noexcept
    : ListRpcResponse() {
    *this = ::std::move(from);
  }

  inline ListRpcResponse& operator=(const ListRpcResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ListRpcResponse& operator=(ListRpcResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ListRpcResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ListRpcResponse* internal_default_instance() {
    return reinterpret_cast<const ListRpcResponse*>(
               &_ListRpcResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ListRpcResponse& a, ListRpcResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ListRpcResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ListRpcResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ListRpcResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ListRpcResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ListRpcResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ListRpcResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ListRpcResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tiny_muduo_rpc.ListRpcResponse";
  }
  protected:
  explicit ListRpcResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServiceNameFieldNumber = 2,
    kMethodNameFieldNumber = 3,
    kErrorFieldNumber = 1,
  };
  // repeated string service_name = 2;
  int service_name_size() const;
  private:
  int _internal_service_name_size() const;
  public:
  void clear_service_name();
  const std::string& service_name(int index) const;
  std::string* mutable_service_name(int index);
  void set_service_name(int index, const std::string& value);
  void set_service_name(int index, std::string&& value);
  void set_service_name(int index, const char* value);
  void set_service_name(int index, const char* value, size_t size);
  std::string* add_service_name();
  void add_service_name(const std::string& value);
  void add_service_name(std::string&& value);
  void add_service_name(const char* value);
  void add_service_name(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& service_name() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_service_name();
  private:
  const std::string& _internal_service_name(int index) const;
  std::string* _internal_add_service_name();
  public:

  // repeated string method_name = 3;
  int method_name_size() const;
  private:
  int _internal_method_name_size() const;
  public:
  void clear_method_name();
  const std::string& method_name(int index) const;
  std::string* mutable_method_name(int index);
  void set_method_name(int index, const std::string& value);
  void set_method_name(int index, std::string&& value);
  void set_method_name(int index, const char* value);
  void set_method_name(int index, const char* value, size_t size);
  std::string* add_method_name();
  void add_method_name(const std::string& value);
  void add_method_name(std::string&& value);
  void add_method_name(const char* value);
  void add_method_name(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& method_name() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_method_name();
  private:
  const std::string& _internal_method_name(int index) const;
  std::string* _internal_add_method_name();
  public:

  // .tiny_muduo_rpc.ErrorCode error = 1;
  void clear_error();
  ::tiny_muduo_rpc::ErrorCode error() const;
  void set_error(::tiny_muduo_rpc::ErrorCode value);
  private:
  ::tiny_muduo_rpc::ErrorCode _internal_error() const;
  void _internal_set_error(::tiny_muduo_rpc::ErrorCode value);
  public:

  // @@protoc_insertion_point(class_scope:tiny_muduo_rpc.ListRpcResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> service_name_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> method_name_;
  int error_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_rpcservice_2eproto;
};
// -------------------------------------------------------------------

class GetServiceRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tiny_muduo_rpc.GetServiceRequest) */ {
 public:
  inline GetServiceRequest() : GetServiceRequest(nullptr) {}
  ~GetServiceRequest() override;
  explicit PROTOBUF_CONSTEXPR GetServiceRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetServiceRequest(const GetServiceRequest& from);
  GetServiceRequest(GetServiceRequest&& from) noexcept
    : GetServiceRequest() {
    *this = ::std::move(from);
  }

  inline GetServiceRequest& operator=(const GetServiceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetServiceRequest& operator=(GetServiceRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetServiceRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetServiceRequest* internal_default_instance() {
    return reinterpret_cast<const GetServiceRequest*>(
               &_GetServiceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GetServiceRequest& a, GetServiceRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetServiceRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetServiceRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetServiceRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetServiceRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetServiceRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const GetServiceRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetServiceRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tiny_muduo_rpc.GetServiceRequest";
  }
  protected:
  explicit GetServiceRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServiceNameFieldNumber = 1,
  };
  // string service_name = 1;
  void clear_service_name();
  const std::string& service_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_service_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_service_name();
  PROTOBUF_NODISCARD std::string* release_service_name();
  void set_allocated_service_name(std::string* service_name);
  private:
  const std::string& _internal_service_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_service_name(const std::string& value);
  std::string* _internal_mutable_service_name();
  public:

  // @@protoc_insertion_point(class_scope:tiny_muduo_rpc.GetServiceRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr service_name_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_rpcservice_2eproto;
};
// -------------------------------------------------------------------

class GetServiceResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tiny_muduo_rpc.GetServiceResponse) */ {
 public:
  inline GetServiceResponse() : GetServiceResponse(nullptr) {}
  ~GetServiceResponse() override;
  explicit PROTOBUF_CONSTEXPR GetServiceResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetServiceResponse(const GetServiceResponse& from);
  GetServiceResponse(GetServiceResponse&& from) noexcept
    : GetServiceResponse() {
    *this = ::std::move(from);
  }

  inline GetServiceResponse& operator=(const GetServiceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetServiceResponse& operator=(GetServiceResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetServiceResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetServiceResponse* internal_default_instance() {
    return reinterpret_cast<const GetServiceResponse*>(
               &_GetServiceResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(GetServiceResponse& a, GetServiceResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetServiceResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetServiceResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetServiceResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetServiceResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetServiceResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const GetServiceResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetServiceResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tiny_muduo_rpc.GetServiceResponse";
  }
  protected:
  explicit GetServiceResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kProtoFileFieldNumber = 2,
    kProtoFileNameFieldNumber = 3,
    kErrorFieldNumber = 1,
  };
  // repeated string proto_file = 2;
  int proto_file_size() const;
  private:
  int _internal_proto_file_size() const;
  public:
  void clear_proto_file();
  const std::string& proto_file(int index) const;
  std::string* mutable_proto_file(int index);
  void set_proto_file(int index, const std::string& value);
  void set_proto_file(int index, std::string&& value);
  void set_proto_file(int index, const char* value);
  void set_proto_file(int index, const char* value, size_t size);
  std::string* add_proto_file();
  void add_proto_file(const std::string& value);
  void add_proto_file(std::string&& value);
  void add_proto_file(const char* value);
  void add_proto_file(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& proto_file() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_proto_file();
  private:
  const std::string& _internal_proto_file(int index) const;
  std::string* _internal_add_proto_file();
  public:

  // repeated string proto_file_name = 3;
  int proto_file_name_size() const;
  private:
  int _internal_proto_file_name_size() const;
  public:
  void clear_proto_file_name();
  const std::string& proto_file_name(int index) const;
  std::string* mutable_proto_file_name(int index);
  void set_proto_file_name(int index, const std::string& value);
  void set_proto_file_name(int index, std::string&& value);
  void set_proto_file_name(int index, const char* value);
  void set_proto_file_name(int index, const char* value, size_t size);
  std::string* add_proto_file_name();
  void add_proto_file_name(const std::string& value);
  void add_proto_file_name(std::string&& value);
  void add_proto_file_name(const char* value);
  void add_proto_file_name(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& proto_file_name() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_proto_file_name();
  private:
  const std::string& _internal_proto_file_name(int index) const;
  std::string* _internal_add_proto_file_name();
  public:

  // .tiny_muduo_rpc.ErrorCode error = 1;
  void clear_error();
  ::tiny_muduo_rpc::ErrorCode error() const;
  void set_error(::tiny_muduo_rpc::ErrorCode value);
  private:
  ::tiny_muduo_rpc::ErrorCode _internal_error() const;
  void _internal_set_error(::tiny_muduo_rpc::ErrorCode value);
  public:

  // @@protoc_insertion_point(class_scope:tiny_muduo_rpc.GetServiceResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> proto_file_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> proto_file_name_;
  int error_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_rpcservice_2eproto;
};
// ===================================================================

class RpcService_Stub;

class RpcService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline RpcService() {};
 public:
  virtual ~RpcService();

  typedef RpcService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void listRpc(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::tiny_muduo_rpc::ListRpcRequest* request,
                       ::tiny_muduo_rpc::ListRpcResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void getService(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::tiny_muduo_rpc::GetServiceRequest* request,
                       ::tiny_muduo_rpc::GetServiceResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(RpcService);
};

class RpcService_Stub : public RpcService {
 public:
  RpcService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  RpcService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~RpcService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements RpcService ------------------------------------------

  void listRpc(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::tiny_muduo_rpc::ListRpcRequest* request,
                       ::tiny_muduo_rpc::ListRpcResponse* response,
                       ::google::protobuf::Closure* done);
  void getService(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::tiny_muduo_rpc::GetServiceRequest* request,
                       ::tiny_muduo_rpc::GetServiceResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(RpcService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ListRpcRequest

// string service_name = 1;
inline bool ListRpcRequest::_internal_has_service_name() const {
  return optional_service_name_case() == kServiceName;
}
inline bool ListRpcRequest::has_service_name() const {
  return _internal_has_service_name();
}
inline void ListRpcRequest::set_has_service_name() {
  _oneof_case_[0] = kServiceName;
}
inline void ListRpcRequest::clear_service_name() {
  if (_internal_has_service_name()) {
    optional_service_name_.service_name_.Destroy();
    clear_has_optional_service_name();
  }
}
inline const std::string& ListRpcRequest::service_name() const {
  // @@protoc_insertion_point(field_get:tiny_muduo_rpc.ListRpcRequest.service_name)
  return _internal_service_name();
}
template <typename ArgT0, typename... ArgT>
inline void ListRpcRequest::set_service_name(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_service_name()) {
    clear_optional_service_name();
    set_has_service_name();
    optional_service_name_.service_name_.InitDefault();
  }
  optional_service_name_.service_name_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tiny_muduo_rpc.ListRpcRequest.service_name)
}
inline std::string* ListRpcRequest::mutable_service_name() {
  std::string* _s = _internal_mutable_service_name();
  // @@protoc_insertion_point(field_mutable:tiny_muduo_rpc.ListRpcRequest.service_name)
  return _s;
}
inline const std::string& ListRpcRequest::_internal_service_name() const {
  if (_internal_has_service_name()) {
    return optional_service_name_.service_name_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void ListRpcRequest::_internal_set_service_name(const std::string& value) {
  if (!_internal_has_service_name()) {
    clear_optional_service_name();
    set_has_service_name();
    optional_service_name_.service_name_.InitDefault();
  }
  optional_service_name_.service_name_.Set(value, GetArenaForAllocation());
}
inline std::string* ListRpcRequest::_internal_mutable_service_name() {
  if (!_internal_has_service_name()) {
    clear_optional_service_name();
    set_has_service_name();
    optional_service_name_.service_name_.InitDefault();
  }
  return optional_service_name_.service_name_.Mutable(      GetArenaForAllocation());
}
inline std::string* ListRpcRequest::release_service_name() {
  // @@protoc_insertion_point(field_release:tiny_muduo_rpc.ListRpcRequest.service_name)
  if (_internal_has_service_name()) {
    clear_has_optional_service_name();
    return optional_service_name_.service_name_.Release();
  } else {
    return nullptr;
  }
}
inline void ListRpcRequest::set_allocated_service_name(std::string* service_name) {
  if (has_optional_service_name()) {
    clear_optional_service_name();
  }
  if (service_name != nullptr) {
    set_has_service_name();
    optional_service_name_.service_name_.InitAllocated(service_name, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:tiny_muduo_rpc.ListRpcRequest.service_name)
}

// bool list_method = 2;
inline bool ListRpcRequest::_internal_has_list_method() const {
  return optional_list_method_case() == kListMethod;
}
inline bool ListRpcRequest::has_list_method() const {
  return _internal_has_list_method();
}
inline void ListRpcRequest::set_has_list_method() {
  _oneof_case_[1] = kListMethod;
}
inline void ListRpcRequest::clear_list_method() {
  if (_internal_has_list_method()) {
    optional_list_method_.list_method_ = false;
    clear_has_optional_list_method();
  }
}
inline bool ListRpcRequest::_internal_list_method() const {
  if (_internal_has_list_method()) {
    return optional_list_method_.list_method_;
  }
  return false;
}
inline void ListRpcRequest::_internal_set_list_method(bool value) {
  if (!_internal_has_list_method()) {
    clear_optional_list_method();
    set_has_list_method();
  }
  optional_list_method_.list_method_ = value;
}
inline bool ListRpcRequest::list_method() const {
  // @@protoc_insertion_point(field_get:tiny_muduo_rpc.ListRpcRequest.list_method)
  return _internal_list_method();
}
inline void ListRpcRequest::set_list_method(bool value) {
  _internal_set_list_method(value);
  // @@protoc_insertion_point(field_set:tiny_muduo_rpc.ListRpcRequest.list_method)
}

inline bool ListRpcRequest::has_optional_service_name() const {
  return optional_service_name_case() != OPTIONAL_SERVICE_NAME_NOT_SET;
}
inline void ListRpcRequest::clear_has_optional_service_name() {
  _oneof_case_[0] = OPTIONAL_SERVICE_NAME_NOT_SET;
}
inline bool ListRpcRequest::has_optional_list_method() const {
  return optional_list_method_case() != OPTIONAL_LIST_METHOD_NOT_SET;
}
inline void ListRpcRequest::clear_has_optional_list_method() {
  _oneof_case_[1] = OPTIONAL_LIST_METHOD_NOT_SET;
}
inline ListRpcRequest::OptionalServiceNameCase ListRpcRequest::optional_service_name_case() const {
  return ListRpcRequest::OptionalServiceNameCase(_oneof_case_[0]);
}
inline ListRpcRequest::OptionalListMethodCase ListRpcRequest::optional_list_method_case() const {
  return ListRpcRequest::OptionalListMethodCase(_oneof_case_[1]);
}
// -------------------------------------------------------------------

// ListRpcResponse

// .tiny_muduo_rpc.ErrorCode error = 1;
inline void ListRpcResponse::clear_error() {
  error_ = 0;
}
inline ::tiny_muduo_rpc::ErrorCode ListRpcResponse::_internal_error() const {
  return static_cast< ::tiny_muduo_rpc::ErrorCode >(error_);
}
inline ::tiny_muduo_rpc::ErrorCode ListRpcResponse::error() const {
  // @@protoc_insertion_point(field_get:tiny_muduo_rpc.ListRpcResponse.error)
  return _internal_error();
}
inline void ListRpcResponse::_internal_set_error(::tiny_muduo_rpc::ErrorCode value) {
  
  error_ = value;
}
inline void ListRpcResponse::set_error(::tiny_muduo_rpc::ErrorCode value) {
  _internal_set_error(value);
  // @@protoc_insertion_point(field_set:tiny_muduo_rpc.ListRpcResponse.error)
}

// repeated string service_name = 2;
inline int ListRpcResponse::_internal_service_name_size() const {
  return service_name_.size();
}
inline int ListRpcResponse::service_name_size() const {
  return _internal_service_name_size();
}
inline void ListRpcResponse::clear_service_name() {
  service_name_.Clear();
}
inline std::string* ListRpcResponse::add_service_name() {
  std::string* _s = _internal_add_service_name();
  // @@protoc_insertion_point(field_add_mutable:tiny_muduo_rpc.ListRpcResponse.service_name)
  return _s;
}
inline const std::string& ListRpcResponse::_internal_service_name(int index) const {
  return service_name_.Get(index);
}
inline const std::string& ListRpcResponse::service_name(int index) const {
  // @@protoc_insertion_point(field_get:tiny_muduo_rpc.ListRpcResponse.service_name)
  return _internal_service_name(index);
}
inline std::string* ListRpcResponse::mutable_service_name(int index) {
  // @@protoc_insertion_point(field_mutable:tiny_muduo_rpc.ListRpcResponse.service_name)
  return service_name_.Mutable(index);
}
inline void ListRpcResponse::set_service_name(int index, const std::string& value) {
  service_name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:tiny_muduo_rpc.ListRpcResponse.service_name)
}
inline void ListRpcResponse::set_service_name(int index, std::string&& value) {
  service_name_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:tiny_muduo_rpc.ListRpcResponse.service_name)
}
inline void ListRpcResponse::set_service_name(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  service_name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:tiny_muduo_rpc.ListRpcResponse.service_name)
}
inline void ListRpcResponse::set_service_name(int index, const char* value, size_t size) {
  service_name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:tiny_muduo_rpc.ListRpcResponse.service_name)
}
inline std::string* ListRpcResponse::_internal_add_service_name() {
  return service_name_.Add();
}
inline void ListRpcResponse::add_service_name(const std::string& value) {
  service_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:tiny_muduo_rpc.ListRpcResponse.service_name)
}
inline void ListRpcResponse::add_service_name(std::string&& value) {
  service_name_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:tiny_muduo_rpc.ListRpcResponse.service_name)
}
inline void ListRpcResponse::add_service_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  service_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:tiny_muduo_rpc.ListRpcResponse.service_name)
}
inline void ListRpcResponse::add_service_name(const char* value, size_t size) {
  service_name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:tiny_muduo_rpc.ListRpcResponse.service_name)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
ListRpcResponse::service_name() const {
  // @@protoc_insertion_point(field_list:tiny_muduo_rpc.ListRpcResponse.service_name)
  return service_name_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
ListRpcResponse::mutable_service_name() {
  // @@protoc_insertion_point(field_mutable_list:tiny_muduo_rpc.ListRpcResponse.service_name)
  return &service_name_;
}

// repeated string method_name = 3;
inline int ListRpcResponse::_internal_method_name_size() const {
  return method_name_.size();
}
inline int ListRpcResponse::method_name_size() const {
  return _internal_method_name_size();
}
inline void ListRpcResponse::clear_method_name() {
  method_name_.Clear();
}
inline std::string* ListRpcResponse::add_method_name() {
  std::string* _s = _internal_add_method_name();
  // @@protoc_insertion_point(field_add_mutable:tiny_muduo_rpc.ListRpcResponse.method_name)
  return _s;
}
inline const std::string& ListRpcResponse::_internal_method_name(int index) const {
  return method_name_.Get(index);
}
inline const std::string& ListRpcResponse::method_name(int index) const {
  // @@protoc_insertion_point(field_get:tiny_muduo_rpc.ListRpcResponse.method_name)
  return _internal_method_name(index);
}
inline std::string* ListRpcResponse::mutable_method_name(int index) {
  // @@protoc_insertion_point(field_mutable:tiny_muduo_rpc.ListRpcResponse.method_name)
  return method_name_.Mutable(index);
}
inline void ListRpcResponse::set_method_name(int index, const std::string& value) {
  method_name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:tiny_muduo_rpc.ListRpcResponse.method_name)
}
inline void ListRpcResponse::set_method_name(int index, std::string&& value) {
  method_name_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:tiny_muduo_rpc.ListRpcResponse.method_name)
}
inline void ListRpcResponse::set_method_name(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  method_name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:tiny_muduo_rpc.ListRpcResponse.method_name)
}
inline void ListRpcResponse::set_method_name(int index, const char* value, size_t size) {
  method_name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:tiny_muduo_rpc.ListRpcResponse.method_name)
}
inline std::string* ListRpcResponse::_internal_add_method_name() {
  return method_name_.Add();
}
inline void ListRpcResponse::add_method_name(const std::string& value) {
  method_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:tiny_muduo_rpc.ListRpcResponse.method_name)
}
inline void ListRpcResponse::add_method_name(std::string&& value) {
  method_name_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:tiny_muduo_rpc.ListRpcResponse.method_name)
}
inline void ListRpcResponse::add_method_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  method_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:tiny_muduo_rpc.ListRpcResponse.method_name)
}
inline void ListRpcResponse::add_method_name(const char* value, size_t size) {
  method_name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:tiny_muduo_rpc.ListRpcResponse.method_name)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
ListRpcResponse::method_name() const {
  // @@protoc_insertion_point(field_list:tiny_muduo_rpc.ListRpcResponse.method_name)
  return method_name_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
ListRpcResponse::mutable_method_name() {
  // @@protoc_insertion_point(field_mutable_list:tiny_muduo_rpc.ListRpcResponse.method_name)
  return &method_name_;
}

// -------------------------------------------------------------------

// GetServiceRequest

// string service_name = 1;
inline void GetServiceRequest::clear_service_name() {
  service_name_.ClearToEmpty();
}
inline const std::string& GetServiceRequest::service_name() const {
  // @@protoc_insertion_point(field_get:tiny_muduo_rpc.GetServiceRequest.service_name)
  return _internal_service_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetServiceRequest::set_service_name(ArgT0&& arg0, ArgT... args) {
 
 service_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tiny_muduo_rpc.GetServiceRequest.service_name)
}
inline std::string* GetServiceRequest::mutable_service_name() {
  std::string* _s = _internal_mutable_service_name();
  // @@protoc_insertion_point(field_mutable:tiny_muduo_rpc.GetServiceRequest.service_name)
  return _s;
}
inline const std::string& GetServiceRequest::_internal_service_name() const {
  return service_name_.Get();
}
inline void GetServiceRequest::_internal_set_service_name(const std::string& value) {
  
  service_name_.Set(value, GetArenaForAllocation());
}
inline std::string* GetServiceRequest::_internal_mutable_service_name() {
  
  return service_name_.Mutable(GetArenaForAllocation());
}
inline std::string* GetServiceRequest::release_service_name() {
  // @@protoc_insertion_point(field_release:tiny_muduo_rpc.GetServiceRequest.service_name)
  return service_name_.Release();
}
inline void GetServiceRequest::set_allocated_service_name(std::string* service_name) {
  if (service_name != nullptr) {
    
  } else {
    
  }
  service_name_.SetAllocated(service_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (service_name_.IsDefault()) {
    service_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tiny_muduo_rpc.GetServiceRequest.service_name)
}

// -------------------------------------------------------------------

// GetServiceResponse

// .tiny_muduo_rpc.ErrorCode error = 1;
inline void GetServiceResponse::clear_error() {
  error_ = 0;
}
inline ::tiny_muduo_rpc::ErrorCode GetServiceResponse::_internal_error() const {
  return static_cast< ::tiny_muduo_rpc::ErrorCode >(error_);
}
inline ::tiny_muduo_rpc::ErrorCode GetServiceResponse::error() const {
  // @@protoc_insertion_point(field_get:tiny_muduo_rpc.GetServiceResponse.error)
  return _internal_error();
}
inline void GetServiceResponse::_internal_set_error(::tiny_muduo_rpc::ErrorCode value) {
  
  error_ = value;
}
inline void GetServiceResponse::set_error(::tiny_muduo_rpc::ErrorCode value) {
  _internal_set_error(value);
  // @@protoc_insertion_point(field_set:tiny_muduo_rpc.GetServiceResponse.error)
}

// repeated string proto_file = 2;
inline int GetServiceResponse::_internal_proto_file_size() const {
  return proto_file_.size();
}
inline int GetServiceResponse::proto_file_size() const {
  return _internal_proto_file_size();
}
inline void GetServiceResponse::clear_proto_file() {
  proto_file_.Clear();
}
inline std::string* GetServiceResponse::add_proto_file() {
  std::string* _s = _internal_add_proto_file();
  // @@protoc_insertion_point(field_add_mutable:tiny_muduo_rpc.GetServiceResponse.proto_file)
  return _s;
}
inline const std::string& GetServiceResponse::_internal_proto_file(int index) const {
  return proto_file_.Get(index);
}
inline const std::string& GetServiceResponse::proto_file(int index) const {
  // @@protoc_insertion_point(field_get:tiny_muduo_rpc.GetServiceResponse.proto_file)
  return _internal_proto_file(index);
}
inline std::string* GetServiceResponse::mutable_proto_file(int index) {
  // @@protoc_insertion_point(field_mutable:tiny_muduo_rpc.GetServiceResponse.proto_file)
  return proto_file_.Mutable(index);
}
inline void GetServiceResponse::set_proto_file(int index, const std::string& value) {
  proto_file_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:tiny_muduo_rpc.GetServiceResponse.proto_file)
}
inline void GetServiceResponse::set_proto_file(int index, std::string&& value) {
  proto_file_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:tiny_muduo_rpc.GetServiceResponse.proto_file)
}
inline void GetServiceResponse::set_proto_file(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  proto_file_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:tiny_muduo_rpc.GetServiceResponse.proto_file)
}
inline void GetServiceResponse::set_proto_file(int index, const char* value, size_t size) {
  proto_file_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:tiny_muduo_rpc.GetServiceResponse.proto_file)
}
inline std::string* GetServiceResponse::_internal_add_proto_file() {
  return proto_file_.Add();
}
inline void GetServiceResponse::add_proto_file(const std::string& value) {
  proto_file_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:tiny_muduo_rpc.GetServiceResponse.proto_file)
}
inline void GetServiceResponse::add_proto_file(std::string&& value) {
  proto_file_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:tiny_muduo_rpc.GetServiceResponse.proto_file)
}
inline void GetServiceResponse::add_proto_file(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  proto_file_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:tiny_muduo_rpc.GetServiceResponse.proto_file)
}
inline void GetServiceResponse::add_proto_file(const char* value, size_t size) {
  proto_file_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:tiny_muduo_rpc.GetServiceResponse.proto_file)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
GetServiceResponse::proto_file() const {
  // @@protoc_insertion_point(field_list:tiny_muduo_rpc.GetServiceResponse.proto_file)
  return proto_file_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
GetServiceResponse::mutable_proto_file() {
  // @@protoc_insertion_point(field_mutable_list:tiny_muduo_rpc.GetServiceResponse.proto_file)
  return &proto_file_;
}

// repeated string proto_file_name = 3;
inline int GetServiceResponse::_internal_proto_file_name_size() const {
  return proto_file_name_.size();
}
inline int GetServiceResponse::proto_file_name_size() const {
  return _internal_proto_file_name_size();
}
inline void GetServiceResponse::clear_proto_file_name() {
  proto_file_name_.Clear();
}
inline std::string* GetServiceResponse::add_proto_file_name() {
  std::string* _s = _internal_add_proto_file_name();
  // @@protoc_insertion_point(field_add_mutable:tiny_muduo_rpc.GetServiceResponse.proto_file_name)
  return _s;
}
inline const std::string& GetServiceResponse::_internal_proto_file_name(int index) const {
  return proto_file_name_.Get(index);
}
inline const std::string& GetServiceResponse::proto_file_name(int index) const {
  // @@protoc_insertion_point(field_get:tiny_muduo_rpc.GetServiceResponse.proto_file_name)
  return _internal_proto_file_name(index);
}
inline std::string* GetServiceResponse::mutable_proto_file_name(int index) {
  // @@protoc_insertion_point(field_mutable:tiny_muduo_rpc.GetServiceResponse.proto_file_name)
  return proto_file_name_.Mutable(index);
}
inline void GetServiceResponse::set_proto_file_name(int index, const std::string& value) {
  proto_file_name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:tiny_muduo_rpc.GetServiceResponse.proto_file_name)
}
inline void GetServiceResponse::set_proto_file_name(int index, std::string&& value) {
  proto_file_name_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:tiny_muduo_rpc.GetServiceResponse.proto_file_name)
}
inline void GetServiceResponse::set_proto_file_name(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  proto_file_name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:tiny_muduo_rpc.GetServiceResponse.proto_file_name)
}
inline void GetServiceResponse::set_proto_file_name(int index, const char* value, size_t size) {
  proto_file_name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:tiny_muduo_rpc.GetServiceResponse.proto_file_name)
}
inline std::string* GetServiceResponse::_internal_add_proto_file_name() {
  return proto_file_name_.Add();
}
inline void GetServiceResponse::add_proto_file_name(const std::string& value) {
  proto_file_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:tiny_muduo_rpc.GetServiceResponse.proto_file_name)
}
inline void GetServiceResponse::add_proto_file_name(std::string&& value) {
  proto_file_name_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:tiny_muduo_rpc.GetServiceResponse.proto_file_name)
}
inline void GetServiceResponse::add_proto_file_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  proto_file_name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:tiny_muduo_rpc.GetServiceResponse.proto_file_name)
}
inline void GetServiceResponse::add_proto_file_name(const char* value, size_t size) {
  proto_file_name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:tiny_muduo_rpc.GetServiceResponse.proto_file_name)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
GetServiceResponse::proto_file_name() const {
  // @@protoc_insertion_point(field_list:tiny_muduo_rpc.GetServiceResponse.proto_file_name)
  return proto_file_name_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
GetServiceResponse::mutable_proto_file_name() {
  // @@protoc_insertion_point(field_mutable_list:tiny_muduo_rpc.GetServiceResponse.proto_file_name)
  return &proto_file_name_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace tiny_muduo_rpc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_rpcservice_2eproto
