// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: query.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_query_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_query_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_query_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_query_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_query_2eproto;
namespace tiny_muduo {
class Answer;
struct AnswerDefaultTypeInternal;
extern AnswerDefaultTypeInternal _Answer_default_instance_;
class Empty;
struct EmptyDefaultTypeInternal;
extern EmptyDefaultTypeInternal _Empty_default_instance_;
class Query;
struct QueryDefaultTypeInternal;
extern QueryDefaultTypeInternal _Query_default_instance_;
}  // namespace tiny_muduo
PROTOBUF_NAMESPACE_OPEN
template<> ::tiny_muduo::Answer* Arena::CreateMaybeMessage<::tiny_muduo::Answer>(Arena*);
template<> ::tiny_muduo::Empty* Arena::CreateMaybeMessage<::tiny_muduo::Empty>(Arena*);
template<> ::tiny_muduo::Query* Arena::CreateMaybeMessage<::tiny_muduo::Query>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace tiny_muduo {

// ===================================================================

class Query final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tiny_muduo.Query) */ {
 public:
  inline Query() : Query(nullptr) {}
  ~Query() override;
  explicit PROTOBUF_CONSTEXPR Query(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Query(const Query& from);
  Query(Query&& from) noexcept
    : Query() {
    *this = ::std::move(from);
  }

  inline Query& operator=(const Query& from) {
    CopyFrom(from);
    return *this;
  }
  inline Query& operator=(Query&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Query& default_instance() {
    return *internal_default_instance();
  }
  static inline const Query* internal_default_instance() {
    return reinterpret_cast<const Query*>(
               &_Query_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Query& a, Query& b) {
    a.Swap(&b);
  }
  inline void Swap(Query* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Query* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Query* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Query>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Query& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Query& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Query* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tiny_muduo.Query";
  }
  protected:
  explicit Query(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kQuestionerFieldNumber = 2,
    kQuestionFieldNumber = 3,
    kIdFieldNumber = 1,
  };
  // string questioner = 2;
  void clear_questioner();
  const std::string& questioner() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_questioner(ArgT0&& arg0, ArgT... args);
  std::string* mutable_questioner();
  PROTOBUF_NODISCARD std::string* release_questioner();
  void set_allocated_questioner(std::string* questioner);
  private:
  const std::string& _internal_questioner() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_questioner(const std::string& value);
  std::string* _internal_mutable_questioner();
  public:

  // string question = 3;
  void clear_question();
  const std::string& question() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_question(ArgT0&& arg0, ArgT... args);
  std::string* mutable_question();
  PROTOBUF_NODISCARD std::string* release_question();
  void set_allocated_question(std::string* question);
  private:
  const std::string& _internal_question() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_question(const std::string& value);
  std::string* _internal_mutable_question();
  public:

  // int64 id = 1;
  void clear_id();
  int64_t id() const;
  void set_id(int64_t value);
  private:
  int64_t _internal_id() const;
  void _internal_set_id(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:tiny_muduo.Query)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr questioner_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr question_;
  int64_t id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_query_2eproto;
};
// -------------------------------------------------------------------

class Answer final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tiny_muduo.Answer) */ {
 public:
  inline Answer() : Answer(nullptr) {}
  ~Answer() override;
  explicit PROTOBUF_CONSTEXPR Answer(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Answer(const Answer& from);
  Answer(Answer&& from) noexcept
    : Answer() {
    *this = ::std::move(from);
  }

  inline Answer& operator=(const Answer& from) {
    CopyFrom(from);
    return *this;
  }
  inline Answer& operator=(Answer&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Answer& default_instance() {
    return *internal_default_instance();
  }
  static inline const Answer* internal_default_instance() {
    return reinterpret_cast<const Answer*>(
               &_Answer_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Answer& a, Answer& b) {
    a.Swap(&b);
  }
  inline void Swap(Answer* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Answer* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Answer* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Answer>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Answer& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Answer& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Answer* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tiny_muduo.Answer";
  }
  protected:
  explicit Answer(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kQuestionerFieldNumber = 2,
    kAnswererFieldNumber = 3,
    kSolutionFieldNumber = 4,
    kIdFieldNumber = 1,
  };
  // string questioner = 2;
  void clear_questioner();
  const std::string& questioner() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_questioner(ArgT0&& arg0, ArgT... args);
  std::string* mutable_questioner();
  PROTOBUF_NODISCARD std::string* release_questioner();
  void set_allocated_questioner(std::string* questioner);
  private:
  const std::string& _internal_questioner() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_questioner(const std::string& value);
  std::string* _internal_mutable_questioner();
  public:

  // string answerer = 3;
  void clear_answerer();
  const std::string& answerer() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_answerer(ArgT0&& arg0, ArgT... args);
  std::string* mutable_answerer();
  PROTOBUF_NODISCARD std::string* release_answerer();
  void set_allocated_answerer(std::string* answerer);
  private:
  const std::string& _internal_answerer() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_answerer(const std::string& value);
  std::string* _internal_mutable_answerer();
  public:

  // string solution = 4;
  void clear_solution();
  const std::string& solution() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_solution(ArgT0&& arg0, ArgT... args);
  std::string* mutable_solution();
  PROTOBUF_NODISCARD std::string* release_solution();
  void set_allocated_solution(std::string* solution);
  private:
  const std::string& _internal_solution() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_solution(const std::string& value);
  std::string* _internal_mutable_solution();
  public:

  // int64 id = 1;
  void clear_id();
  int64_t id() const;
  void set_id(int64_t value);
  private:
  int64_t _internal_id() const;
  void _internal_set_id(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:tiny_muduo.Answer)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr questioner_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr answerer_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr solution_;
  int64_t id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_query_2eproto;
};
// -------------------------------------------------------------------

class Empty final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tiny_muduo.Empty) */ {
 public:
  inline Empty() : Empty(nullptr) {}
  ~Empty() override;
  explicit PROTOBUF_CONSTEXPR Empty(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Empty(const Empty& from);
  Empty(Empty&& from) noexcept
    : Empty() {
    *this = ::std::move(from);
  }

  inline Empty& operator=(const Empty& from) {
    CopyFrom(from);
    return *this;
  }
  inline Empty& operator=(Empty&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Empty& default_instance() {
    return *internal_default_instance();
  }
  static inline const Empty* internal_default_instance() {
    return reinterpret_cast<const Empty*>(
               &_Empty_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Empty& a, Empty& b) {
    a.Swap(&b);
  }
  inline void Swap(Empty* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Empty* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Empty* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Empty>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Empty& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Empty& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Empty* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tiny_muduo.Empty";
  }
  protected:
  explicit Empty(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
  };
  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:tiny_muduo.Empty)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int32_t id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_query_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Query

// int64 id = 1;
inline void Query::clear_id() {
  id_ = int64_t{0};
}
inline int64_t Query::_internal_id() const {
  return id_;
}
inline int64_t Query::id() const {
  // @@protoc_insertion_point(field_get:tiny_muduo.Query.id)
  return _internal_id();
}
inline void Query::_internal_set_id(int64_t value) {
  
  id_ = value;
}
inline void Query::set_id(int64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:tiny_muduo.Query.id)
}

// string questioner = 2;
inline void Query::clear_questioner() {
  questioner_.ClearToEmpty();
}
inline const std::string& Query::questioner() const {
  // @@protoc_insertion_point(field_get:tiny_muduo.Query.questioner)
  return _internal_questioner();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Query::set_questioner(ArgT0&& arg0, ArgT... args) {
 
 questioner_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tiny_muduo.Query.questioner)
}
inline std::string* Query::mutable_questioner() {
  std::string* _s = _internal_mutable_questioner();
  // @@protoc_insertion_point(field_mutable:tiny_muduo.Query.questioner)
  return _s;
}
inline const std::string& Query::_internal_questioner() const {
  return questioner_.Get();
}
inline void Query::_internal_set_questioner(const std::string& value) {
  
  questioner_.Set(value, GetArenaForAllocation());
}
inline std::string* Query::_internal_mutable_questioner() {
  
  return questioner_.Mutable(GetArenaForAllocation());
}
inline std::string* Query::release_questioner() {
  // @@protoc_insertion_point(field_release:tiny_muduo.Query.questioner)
  return questioner_.Release();
}
inline void Query::set_allocated_questioner(std::string* questioner) {
  if (questioner != nullptr) {
    
  } else {
    
  }
  questioner_.SetAllocated(questioner, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (questioner_.IsDefault()) {
    questioner_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tiny_muduo.Query.questioner)
}

// string question = 3;
inline void Query::clear_question() {
  question_.ClearToEmpty();
}
inline const std::string& Query::question() const {
  // @@protoc_insertion_point(field_get:tiny_muduo.Query.question)
  return _internal_question();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Query::set_question(ArgT0&& arg0, ArgT... args) {
 
 question_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tiny_muduo.Query.question)
}
inline std::string* Query::mutable_question() {
  std::string* _s = _internal_mutable_question();
  // @@protoc_insertion_point(field_mutable:tiny_muduo.Query.question)
  return _s;
}
inline const std::string& Query::_internal_question() const {
  return question_.Get();
}
inline void Query::_internal_set_question(const std::string& value) {
  
  question_.Set(value, GetArenaForAllocation());
}
inline std::string* Query::_internal_mutable_question() {
  
  return question_.Mutable(GetArenaForAllocation());
}
inline std::string* Query::release_question() {
  // @@protoc_insertion_point(field_release:tiny_muduo.Query.question)
  return question_.Release();
}
inline void Query::set_allocated_question(std::string* question) {
  if (question != nullptr) {
    
  } else {
    
  }
  question_.SetAllocated(question, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (question_.IsDefault()) {
    question_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tiny_muduo.Query.question)
}

// -------------------------------------------------------------------

// Answer

// int64 id = 1;
inline void Answer::clear_id() {
  id_ = int64_t{0};
}
inline int64_t Answer::_internal_id() const {
  return id_;
}
inline int64_t Answer::id() const {
  // @@protoc_insertion_point(field_get:tiny_muduo.Answer.id)
  return _internal_id();
}
inline void Answer::_internal_set_id(int64_t value) {
  
  id_ = value;
}
inline void Answer::set_id(int64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:tiny_muduo.Answer.id)
}

// string questioner = 2;
inline void Answer::clear_questioner() {
  questioner_.ClearToEmpty();
}
inline const std::string& Answer::questioner() const {
  // @@protoc_insertion_point(field_get:tiny_muduo.Answer.questioner)
  return _internal_questioner();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Answer::set_questioner(ArgT0&& arg0, ArgT... args) {
 
 questioner_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tiny_muduo.Answer.questioner)
}
inline std::string* Answer::mutable_questioner() {
  std::string* _s = _internal_mutable_questioner();
  // @@protoc_insertion_point(field_mutable:tiny_muduo.Answer.questioner)
  return _s;
}
inline const std::string& Answer::_internal_questioner() const {
  return questioner_.Get();
}
inline void Answer::_internal_set_questioner(const std::string& value) {
  
  questioner_.Set(value, GetArenaForAllocation());
}
inline std::string* Answer::_internal_mutable_questioner() {
  
  return questioner_.Mutable(GetArenaForAllocation());
}
inline std::string* Answer::release_questioner() {
  // @@protoc_insertion_point(field_release:tiny_muduo.Answer.questioner)
  return questioner_.Release();
}
inline void Answer::set_allocated_questioner(std::string* questioner) {
  if (questioner != nullptr) {
    
  } else {
    
  }
  questioner_.SetAllocated(questioner, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (questioner_.IsDefault()) {
    questioner_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tiny_muduo.Answer.questioner)
}

// string answerer = 3;
inline void Answer::clear_answerer() {
  answerer_.ClearToEmpty();
}
inline const std::string& Answer::answerer() const {
  // @@protoc_insertion_point(field_get:tiny_muduo.Answer.answerer)
  return _internal_answerer();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Answer::set_answerer(ArgT0&& arg0, ArgT... args) {
 
 answerer_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tiny_muduo.Answer.answerer)
}
inline std::string* Answer::mutable_answerer() {
  std::string* _s = _internal_mutable_answerer();
  // @@protoc_insertion_point(field_mutable:tiny_muduo.Answer.answerer)
  return _s;
}
inline const std::string& Answer::_internal_answerer() const {
  return answerer_.Get();
}
inline void Answer::_internal_set_answerer(const std::string& value) {
  
  answerer_.Set(value, GetArenaForAllocation());
}
inline std::string* Answer::_internal_mutable_answerer() {
  
  return answerer_.Mutable(GetArenaForAllocation());
}
inline std::string* Answer::release_answerer() {
  // @@protoc_insertion_point(field_release:tiny_muduo.Answer.answerer)
  return answerer_.Release();
}
inline void Answer::set_allocated_answerer(std::string* answerer) {
  if (answerer != nullptr) {
    
  } else {
    
  }
  answerer_.SetAllocated(answerer, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (answerer_.IsDefault()) {
    answerer_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tiny_muduo.Answer.answerer)
}

// string solution = 4;
inline void Answer::clear_solution() {
  solution_.ClearToEmpty();
}
inline const std::string& Answer::solution() const {
  // @@protoc_insertion_point(field_get:tiny_muduo.Answer.solution)
  return _internal_solution();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Answer::set_solution(ArgT0&& arg0, ArgT... args) {
 
 solution_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tiny_muduo.Answer.solution)
}
inline std::string* Answer::mutable_solution() {
  std::string* _s = _internal_mutable_solution();
  // @@protoc_insertion_point(field_mutable:tiny_muduo.Answer.solution)
  return _s;
}
inline const std::string& Answer::_internal_solution() const {
  return solution_.Get();
}
inline void Answer::_internal_set_solution(const std::string& value) {
  
  solution_.Set(value, GetArenaForAllocation());
}
inline std::string* Answer::_internal_mutable_solution() {
  
  return solution_.Mutable(GetArenaForAllocation());
}
inline std::string* Answer::release_solution() {
  // @@protoc_insertion_point(field_release:tiny_muduo.Answer.solution)
  return solution_.Release();
}
inline void Answer::set_allocated_solution(std::string* solution) {
  if (solution != nullptr) {
    
  } else {
    
  }
  solution_.SetAllocated(solution, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (solution_.IsDefault()) {
    solution_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tiny_muduo.Answer.solution)
}

// -------------------------------------------------------------------

// Empty

// int32 id = 1;
inline void Empty::clear_id() {
  id_ = 0;
}
inline int32_t Empty::_internal_id() const {
  return id_;
}
inline int32_t Empty::id() const {
  // @@protoc_insertion_point(field_get:tiny_muduo.Empty.id)
  return _internal_id();
}
inline void Empty::_internal_set_id(int32_t value) {
  
  id_ = value;
}
inline void Empty::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:tiny_muduo.Empty.id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace tiny_muduo

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_query_2eproto
